[build-system]
requires = ["setuptools>=40.6.0", "wheel", "setuptools_scm", "pybind11>=2.4", "oldest-supported-numpy"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[tool.pytest.ini_options]
norecursedirs = "tests/*"
addopts = "-v"
