#ifndef _CELERITE_VERSION_H_
#define _CELERITE_VERSION_H_

#define CELERITE_VERSION_MAJOR 0
#define CELERITE_VERSION_MINOR 3
#define CELERITE_VERSION_REVISION 0

#define CELERITE_TO_STRING_HELPER(x) #x
#define CELERITE_TO_STRING(x) CELERITE_TO_STRING_HELPER(x)

#define CELERITE_VERSION_STRING CELERITE_TO_STRING(CELERITE_VERSION_MAJOR) "." \
                                CELERITE_TO_STRING(CELERITE_VERSION_MINOR) "." \
                                CELERITE_TO_STRING(CELERITE_VERSION_REVISION)

#endif
