#ifndef _GENRP_VERSION_H_
#define _GENRP_VERSION_H_

#define GENRP_VERSION_MAJOR 0
#define GENRP_VERSION_MINOR 0
#define GENRP_VERSION_REVISION 1

#define GENRP_TO_STRING_HELPER(x) #x
#define GENRP_TO_STRING(x) GENRP_TO_STRING_HELPER(x)

#define GENRP_VERSION_STRING GENRP_TO_STRING(GENRP_VERSION_MAJOR) "." \
                             GENRP_TO_STRING(GENRP_VERSION_MINOR) "." \
                             GENRP_TO_STRING(GENRP_VERSION_REVISION)

#endif
