name: Tutorials
on:
  push:
    branches:
      - main
  pull_request:
    branches:
  release:
    types:
      - published

jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install ".[tutorials]"

      - name: Get theano compiledir
        id: compiledir
        run: |
          python -c "import theano; print('::set-output name=compiledir::' + theano.config.compiledir.split('/')[-1])"

      - name: "Cache ~/.theano"
        uses: actions/cache@v2
        with:
          path: ~/.theano
          key: tutorials-${{ steps.compiledir.outputs.compiledir }}-${{ hashFiles('docs/tutorials/*.py') }}
          restore-keys: |
            tutorials-${{ steps.compiledir.outputs.compiledir }}-
            tutorials-

      - name: Execute the notebooks
        run: |
          jupytext --to ipynb --execute docs/tutorials/*.py

      - uses: actions/upload-artifact@v2
        with:
          name: notebooks-for-${{ github.sha }}
          path: docs/tutorials

      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1.0.0
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
